# Generated by Django 5.0.6 on 2024-05-15 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Gym'), (1, 'Strength'), (2, 'Cardio'), (3, 'Nutrition'), (4, 'Motivation'), (5, 'Weight Loss')], default=0)),
                ('notes', models.TextField()),
                ('cancelled', models.BooleanField(default=False)),
                ('booking_date_time', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
