# Generated by Django 5.0.6 on 2024-05-15 15:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Gym'), (1, 'Strength'), (2, 'Cardio'), (3, 'Nutrition'), (4, 'Motivation'), (5, 'Weight Loss')], default=0)),
                ('Description', models.TextField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=50, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='none', max_length=255, verbose_name='image')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
