# Generated by Django 5.0.6 on 2024-05-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
