# Generated by Django 5.0.6 on 2024-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_sessions_description_alter_sessions_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='session_type',
            field=models.TextField(choices=[(0, 'Gym'), (1, 'Strength'), (2, 'Cardio'), (3, 'Nutrition'), (4, 'Motivation'), (5, 'Weight Loss')], default='Gym'),
        ),
    ]
