# Generated by Django 5.0.6 on 2024-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_sessions_type_alter_sessions_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_type',
            field=models.TextField(choices=[('Gym', 'Gym'), ('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Nutrition', 'Nutrition'), ('Motivation', 'Motivation'), ('Weight Loss', 'Weight Loss')], default='Gym'),
        ),
    ]
