# Generated by Django 5.0.6 on 2024-05-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
    ]
