# Generated by Django 5.0.6 on 2024-05-16 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
