# Generated by Django 5.0.6 on 2024-05-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booking_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking'),
        ),
    ]
