# Generated by Django 5.0.6 on 2024-05-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_appointments_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='available',
        ),
    ]
