# Generated by Django 5.0.6 on 2024-05-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_appointments_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
    ]
