# Generated by Django 5.0.6 on 2024-05-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_booking_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled',
        ),
    ]
