# Generated by Django 3.2.25 on 2024-05-07 20:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Fitness'), (1, 'Lifestyle'), (2, 'Cardio'), (3, 'Nutrition'), (4, 'Motivation'), (5, 'Shopping'), (6, 'Weight')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='none', max_length=255, verbose_name='image'),
        ),
    ]
